### PR TITLE
Mapfish print

### PR DESCRIPTION
**Pull request by voisardf**
Current state of MFP v3 branch for analysis and fixing datasource issues by C2C

DO NOT MERGE!!

### CODE REVIEW

**Comment by sbrunner** [comment]
What will http://localhost:6566/property/get?id=1_14127 return ?

**Comment by kalbermattenm** [comment]
@voisardf is on holidays until Thursday...

I installed his branch on my side and http://localhost:6566/property/get?id=1_14127 returns some geojson:

```
{"type": "FeatureCollection", "features": [{"geometry": {"type": "MultiPolygon", "coordinates": [[[[559517.4747942629, 203771.7460289343], [559507.5524638571, 203786.78650592532], [559494.0800280258, 203807.51817773224], [559491.9189521658, 203810.82828326177], [559489.3898454136, 203809.25829982], [559488.6698530482, 203809.10833235036], [559479.0604780054, 203802.2254314032], [559478.1484217499, 203801.52443462884], [559479.8904840836, 203798.95135136237], [559468.7040535418, 203790.11945405384], [559467.5829849668, 203788.50244970285], [559427.5994693706, 203770.96305045945], [559432.629636932, 203759.90272211493], [559445.80304423, 203734.53400271808], [559456.8714950224, 203739.6168487924], [559487.4826389, 203752.99138406786], [559494.2928860182, 203756.00227090908], [559494.5754880348, 203755.91688217685], [559494.8649847934, 203755.8592530098], [559495.1587392612, 203755.82994479383], [559495.4539221218, 203755.82924790098], [559495.7722064885, 203755.8613049721], [559496.0853541353, 203755.92634830473], [559496.3900962397, 203756.02368100607], [559496.6829716966, 203756.1522190206], [559503.9742575506, 203759.37312226536], [559518.0648028859, 203765.53489397807], [559520.7248822678, 203766.61587157878], [559517.4747942629, 203771.7460289343]]]]}, "type": "Feature", "id": 67487, "properties": {"valide": "V", "datedt": "2004-07-28", "idemai": "1_14127", "numcom": 1, "cadastre": "NEUCHATEL", "nummai": "14127", "mutmai": "N2001", "source": "parcellaire officiel", "mutcou": null, "srfmai": 3431, "typimm": "PARCELLE", "nufeco": null, "url_terris_v2": "<a href=\"javascript:sitn.propWin('1','14127');\">Cliquer ici</a>", "url_mobile": "<a href=\"${ownerUrl}?numcad=1&nummai=14127\" target=_blank>Cliquer ici</a>"}}]}
```

**Comment by sbrunner** [comment]
This server can be publicly accessed?

**Comment by kalbermattenm** [comment]
I am afraid not on this branch... Let me check if I can do something about it...

**Comment by kalbermattenm** [comment]
I just put this dev instance on the mapfish_print branch... I am not totally sure I did all as I should have... Thus, if you encounter strange things, let me know...:

http://sitn.ne.ch/dev_crdppf/

(Do not forget the trailing of this URL, otherwise you will get an error...)

**Comment by sbrunner** [comment]
Thanks @kalbermattenm, I just send en email for the next steps :-)

**Comment by voisardf** [comment]
OK, this branch is not linted, but otherwise working with pdf v2. So I'm merging this one to have a new base.

**Pull request merged**
