### PR TITLE
Removes unneded jars

### PR DESCRIPTION
**Pull request by sbrunner**
Those jars do mixage errors on Jura ...

### CODE REVIEW

**Comment by voisardf** [comment]
Are you sure we don't need the Cadastra fonts?
Otherwise it's fine. Feel free to merge :)

**Comment by sbrunner** [comment]
We have tow jar for Cadastra fonts, I remove witch is not used :-)

**Comment by voisardf** [comment]
👍

**Comment by sbrunner** [comment]
Thanks :-)

**Pull request merged**
