### PR TITLE
Py3

### PR DESCRIPTION
**Pull request by voisardf**
Should fix a bug with the print and sets ApacheTomcat 9 as default

### CODE REVIEW

**Comment by voisardf** [comment]
@sbrunner @sitj-raphael : This PR should fix the issue - I commented the title variable on L423, but I rather think that the single quotes instead of having double quotes on this line where the reason for the issue.

Could you test (with and without the title tag) and give me a feedback if it works?

**Comment by sbrunner** [comment]
I should also do:
```diff
@@ -76,15 +76,17 @@ def set_documents(topicid, doctype, docids, featureinfo, geofilter, doclist):
     if len(docs) > 0:
         doc = ""
         for doc in docs:
-            if doc['title'] == '' or doc['title'] is None:
-                doc['title'] = doc['officialtitle']
             if doc['doctype'] == doctype and doc['documentid'] in docids and doc['documentid'] not in doclist:
-                documents.append({"documentid": doc['documentid'], "officialtitle": doc['officialtitle'], "title": doc['title'], "remoteurl": doc['remoteurl']})
+                documents.append({"documentid": doc['documentid'], "officialtitle": doc['officialtitle'], "remoteurl": doc['remoteurl']})^M
 
             if doc['doctype'] == doctype and geofilter is True and doc['documentid'] not in docids:
-                if doc['title'] == '' or doc['title'] is None:
-                    doc['title'] = doc['officialtitle']
-                documents.append({"documentid": doc['documentid'], "officialtitle": doc['officialtitle'], "title": doc['title'], "remoteurl": doc['remoteurl']})^M
+                documents.append({"documentid": doc['documentid'], "officialtitle": doc['officialtitle'], "remoteurl": doc['remoteurl']})^M
 
     return documents
```

Then I will have:
```
print_1      | Extra Properties: 
print_1      | 
print_1      |  * authorityuuid
print_1      | 
print_1      | All allowed properties are: 
print_1      | 
print_1      |  * authorityname
print_1      |  * authorityurl

```

**Comment by voisardf** [comment]
ok I removed those two too.
What I don't exactly understand is why this error appears now with this elements when it wasn't an issue before? Has the Linux version become more strict than before?
On Windows, no error is thrown for those extra vars though the yaml is configured for it

**Comment by sbrunner** [comment]
No, but it's can be the print version, you looks to use the 3.10.4, and we use the 3.16, I can try with the 3.10 :-)

**Comment by sbrunner** [comment]
I just test the version 3.10.7 and effectively it's working better :-)

**Comment by voisardf** [comment]
Ok, I just downloaded the 3.16.2 war and also the 3.18.x and will test how that works.

But for now, is it possible to use the 3.10.7 for Jura? :-)

**Comment by sbrunner** [comment]
I test it, the last news is that I get an error with the font ...

**Comment by sbrunner** [comment]
Thanks for your support, now it's working for Jura :-)

**Comment by voisardf** [comment]
Cool. :-)
Using 3.16.2 on my side also throws a lot of errors and extra parameters stuff. Obviously the behaviour of the print war changed quite a lot between the versions. So I guess the easiest way is to set
`throwErrorOnExtraParameters: false `
in this case, because it does not matter if there are a few extra vars.

I'll adapt the print proxy to the newest print war in a later version. So closing the issue https://github.com/sitn/crdppf_core/issues/171 as it is solved using 3.10.7 of the print war

**Comment by sbrunner** [comment]
Effectively the `throwErrorOnExtraParameters` catch relay more extra parameters, no objection to set it to `false` :-)

**Comment by voisardf** [comment]
👍

**Comment by voisardf** [comment]
Merging this to set python 3 branch as the new master

**Pull request merged**
