### PR TITLE
Versions cleanup

### PR DESCRIPTION
**Pull request by voisardf**
updating versions and some additions to refactoring done by @kalbermattenm in the PR https://github.com/sitn/crdppf_core/pull/198

thanks for a quick check if I omitted something important regarding to the example on
https://pypi.org/project/zope.sqlalchemy/#usage-in-short

but instance is working locally

### CODE REVIEW

**Comment by kalbermattenm** [comment]
Hmmm... There is something missing... You import `registre` from `zope.sqlalchemy` but nothing is registered... I am on it...

**Comment by voisardf** [comment]
you're right. It seems I just forgot the line
`register(DBSession)`

**Comment by kalbermattenm** [comment]
Yes, I added it... I was not sure about the `register` function....

**Comment by kalbermattenm** [comment]
IHMO, we could merge that.

**Comment by voisardf** [comment]
thanks. Just testing it locally right now with the register line.

**Comment by voisardf** [comment]
Looks good. merging.

**Pull request merged**
