### PR TITLE
fixed filter condition problem with sqlalchemy and legal docs

### PR DESCRIPTION
**Pull request by voisardf**
tite says it all

### CODE REVIEW

**Comment by voisardf** [comment]
strangely enough in sqlalchemy the condition for is None has to be written " == None"

**Comment by voisardf** [comment]
@kalbermattenm: could you do a quick check? Thanks

**Comment by kalbermattenm** [comment]
OK, I do not get why the `is None` is not working... but LGTM, thanks a lot

**Comment by voisardf** [comment]
thanks, merging

**Pull request merged**
