### PR TITLE
cleaning up the bloody mess with the local names table changing attri…

### PR DESCRIPTION
**Pull request by voisardf**
…butes and names faster than you could say stopit and the yet inecplicable difference in xml parsing between development and production server.

### CODE REVIEW

**Comment by voisardf** [comment]
this goes with https://github.com/sitn/crdppf/pull/240

**Comment by voisardf** [comment]
merging

**Comment by kalbermattenm** [comment]
What I do not understand about this issue is why this is actually working for Jura without this correction... Maybe we should ask Jura to test it...

**Comment by voisardf** [comment]
I had the same question, but one possible explanation would be that a difference of the configuration (version of python or eggs) influence the result. It's in fact the only reasonable explanation I've got (for now).
yet to confirm!

**Comment by kalbermattenm** [comment]
Hmmmm... Yeah... Maybe we should ask them to make a clean installation from scratch to be sure that they use the same egg versions as we do...

To discuss....

**Pull request merged**
